demomovieproject/samplemovie/demoapp/urls.py
from django.urls import path
from . import views
app_name='demoapp'
urlpatterns = [
   path('',views.index,name='index'),
   path('movie/<int:movie_id>/',views.detail,name='detail'),
   path('add/',views.add,name='add'),
   path('update/<int:id>/',views.update,name='update'),
   path('delete/<int:id>/', views.delete, name='deleattete'),

]

demomovieproject/samplemovie/samplemovie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

demomovieproject/samplemovie/demoapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
def __str__(self):
    return self.name

demomovieproject/samplemovie/demoapp/forms.py
from django import forms
from .models import Movies
class MovieForms(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

demomovieproject/samplemovie/demoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForms
from .models import Movies


def index(request):
    movie = Movies.objects.all()
    context = {'movie_list': movie}
    return render(request,'index.html',context)


def detail(request, movie_id):
    movie = Movies.objects.get(id=movie_id)
    context1={'movie': movie}
    return render(request,"detail.html",context1)


def add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movies(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')
def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MovieForms(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

demomovieproject/samplemovie/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name">
  <input type="text" name="desc" placeholder="Enter the movie description">
  <input type="text" name="year" placeholder="Enter the movie year">
  <input type="file" name="img">
  <input type="submit">
</form>
{% endblock %}
</body>
</html>

demomovieproject/samplemovie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        Movie Store
    </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

demomovieproject/samplemovie/templates/delete.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure u want to delete third movie
    <input type="submit">
</form>

demomovieproject/samplemovie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
       <div class="col-md-6">
    <img src="{{movie.img.url}}" width="200" height="200">
       </div>
    <div class="col-md-6">
<h4>{{movie.name}}</h4>
<h4>{{movie.desc}}</h4>
<h4>{{movie.year}}</h4>
<a class="btn btn-warning" href="{% url 'demoapp:update' movie.id %}">update</a>
<a class="btn btn-warning" href="{% url 'demoapp:delete' movie.id %}">delete</a>
    </div>
  </div>
</div>
{% endblock %}

demomovieproject/samplemovie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
{% for i in movie_list %}
        <div class="col-md-3">
<div class="card" >
  <img src="{{i.img.url}}" class="card-img-top" alt="" width="100px" height="200px">
  <div class="card-body">
    <h4 class="card-title">{{i.name}}</h4>
    <p class="card-text">{{i.desc}}</p>
      <a href="{% url 'demoapp:detail' i.id %}" class="btn btn-primary"></a>
  </div>
</div>
        </div>
{% endfor %}
    </div>
</div>
{% endblock %}

demomovieproject/samplemovie/templates/update.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>